/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mingren_customviewset_ndk_NdkImageUtil */

#ifndef _Included_com_example_mingren_customviewset_ndk_NdkImageUtil
#define _Included_com_example_mingren_customviewset_ndk_NdkImageUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mingren_customviewset_ndk_NdkImageUtil
 * Method:    getImage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_mingren_customviewset_ndk_NdkImageUtil_getImage
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
